# Generated by Django 3.2.9 on 2021-11-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='params',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='image',
            name='result',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='image',
            name='text_fields',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
